2019-12-05 19:04:15,345 manager INFO 1.1.0
2019-12-05 19:04:15,345 manager INFO Copyright (C) 2003-2010
2019-12-05 19:04:15,345 manager INFO   Noriaki Ando
2019-12-05 19:04:15,345 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-05 19:04:15,345 manager INFO Manager starting.
2019-12-05 19:04:15,345 manager INFO Starting local logging.
2019-12-05 19:04:15,361 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-05 19:04:17,407 ManagerServant INFO Master manager not found
2019-12-05 19:04:17,407 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-05 19:04:17,407 LocalServiceAdmin INFO All the local services are enabled.
2019-12-05 19:04:17,424 ec_base INFO setRate(1000000.000000) done
2019-12-05 19:04:17,424 ec_base INFO setRate(1000.000000) done
2019-12-05 19:04:17,424 rtobject INFO 1 execution context was created.
2019-12-05 19:04:17,424 rtobject INFO Initial active configuration set is default-set.
2019-12-05 19:04:32,312 sensor WARNING buffer empty
2019-12-05 19:04:32,312 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspaces\CsvWrite\CsvWrite.py", line 214, in onExecute
    FSR_dic.setdefault(("FSR" + str(i)), float(data[i-1]))
ValueError: could not convert string to float: None

2019-12-05 19:05:45,854 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-05 19:05:45,854 SdoServiceAdmin ERROR type  already exists.
2019-12-05 19:05:45,855 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-05 19:05:45,855 SdoServiceAdmin ERROR type 7772215a-39dd-47d2-a79e-b92a01f550c6 already exists.
2019-12-05 19:06:01,948 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2019-12-05 19:51:30,532 sign WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\PortBase.py", line 2262, in checkPorts
    if port._non_existent():
  File "C:\Python27\lib\site-packages\omniORB\CORBA.py", line 556, in _non_existent
    return self._obj.nonExistent()
TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

2019-12-05 19:51:30,532 sign WARNING Dead connection: 9c8f7ba1-1746-11ea-ba42-40f02f22cc81
2019-12-05 19:51:31,562 sign WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\PortBase.py", line 836, in disconnect
    return p.notify_disconnect(connector_id)
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTM_IDL\RTC_idl.py", line 1207, in notify_disconnect
    return self._obj.invoke("notify_disconnect", _0_RTC.PortService._d_notify_disconnect, args)
TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

