2019-12-09 16:51:02,163 manager INFO 1.1.0
2019-12-09 16:51:02,163 manager INFO Copyright (C) 2003-2010
2019-12-09 16:51:02,163 manager INFO   Noriaki Ando
2019-12-09 16:51:02,163 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-09 16:51:02,163 manager INFO Manager starting.
2019-12-09 16:51:02,163 manager INFO Starting local logging.
2019-12-09 16:51:02,210 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-09 16:51:04,288 ManagerServant INFO Master manager not found
2019-12-09 16:51:04,288 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-09 16:51:04,288 LocalServiceAdmin INFO All the local services are enabled.
2019-12-09 16:51:04,397 manager INFO Component type conf file: Judge3.conf loaded.
2019-12-09 16:51:04,413 ec_base INFO setRate(1000000.000000) done
2019-12-09 16:51:04,413 ec_base INFO setRate(1000.000000) done
2019-12-09 16:51:04,413 rtobject INFO 1 execution context was created.
2019-12-09 16:51:04,427 rtobject INFO Initial active configuration set is default.
2019-12-09 16:52:38,809 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-09 16:52:38,809 SdoServiceAdmin ERROR type  already exists.
2019-12-09 16:52:38,811 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-09 16:52:38,811 SdoServiceAdmin ERROR type 457dd9c1-a20c-4565-9067-973ec32f4d41 already exists.
2019-12-09 16:54:34,762 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\Judge3\Judge3.py", line 189, in onExecute
    if self._sensor_left_front >= self._sensor_right_front + self._addvalue:
TypeError: unsupported operand type(s) for +: 'float' and 'list'

2019-12-09 16:54:42,026 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\Judge3\Judge3.py", line 189, in onExecute
    if self._sensor_left_front >= self._sensor_right_front + self._addvalue:
TypeError: unsupported operand type(s) for +: 'float' and 'list'

2019-12-09 16:54:45,529 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
