2019-12-07 19:08:54,569 manager INFO 1.1.0
2019-12-07 19:08:54,569 manager INFO Copyright (C) 2003-2010
2019-12-07 19:08:54,569 manager INFO   Noriaki Ando
2019-12-07 19:08:54,569 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-07 19:08:54,569 manager INFO Manager starting.
2019-12-07 19:08:54,569 manager INFO Starting local logging.
2019-12-07 19:08:54,585 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-07 19:08:56,617 ManagerServant INFO Master manager not found
2019-12-07 19:08:56,617 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-07 19:08:56,617 LocalServiceAdmin INFO All the local services are enabled.
2019-12-07 19:08:56,621 manager INFO Component type conf file: Change.conf loaded.
2019-12-07 19:08:56,625 ec_base INFO setRate(1000000.000000) done
2019-12-07 19:08:56,625 ec_base INFO setRate(1000.000000) done
2019-12-07 19:08:56,625 rtobject INFO 1 execution context was created.
2019-12-07 19:08:56,628 rtobject INFO Initial active configuration set is default-set.
2019-12-07 19:09:02,697 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-07 19:09:02,701 SdoServiceAdmin ERROR type  already exists.
2019-12-07 19:09:02,701 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-07 19:09:02,701 SdoServiceAdmin ERROR type cd3ca0a6-415e-4fc2-b393-4a4cd4339024 already exists.
2019-12-07 19:09:11,848 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\Change\Change.py", line 128, in onExecute
    data_new = data.strip()
AttributeError: 'list' object has no attribute 'strip'

2019-12-07 19:09:18,999 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2019-12-07 19:09:25,075 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\Change\Change.py", line 128, in onExecute
    data_new = data.strip()
AttributeError: 'list' object has no attribute 'strip'

2019-12-07 19:13:32,427 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-07 19:13:32,427 SdoServiceAdmin ERROR type  already exists.
2019-12-07 19:13:32,427 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-07 19:13:32,427 SdoServiceAdmin ERROR type c1564934-35bf-4369-86ec-40b5dbbf17d2 already exists.
